# Generated by Django 5.2.5 on 2026-03-04 20:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0010_answer_notes_userdocument_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_tr',
            field=models.TextField(blank=True, verbose_name='Description (Turkish)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name (English)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_tr',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name (Turkish)'),
        ),
        migrations.AddField(
            model_name='choice',
            name='text_en',
            field=models.CharField(blank=True, max_length=500, verbose_name='Choice Text (English)'),
        ),
        migrations.AddField(
            model_name='choice',
            name='text_tr',
            field=models.CharField(blank=True, max_length=500, verbose_name='Choice Text (Turkish)'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_en',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Question Text (English)'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_tr',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Question Text (Turkish)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='description_tr',
            field=models.TextField(blank=True, verbose_name='Description (Turkish)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Survey Name (English)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='name_tr',
            field=models.CharField(blank=True, max_length=200, verbose_name='Survey Name (Turkish)'),
        ),
    ]
