# Generated by Django 5.0.6 on 2026-03-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_category_description_en_category_description_tr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='text_answer',
            field=models.TextField(blank=True, help_text='Open-ended text answer for text-type questions', null=True, verbose_name='Text Answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('choice', 'Choice (select from options)'), ('text', 'Text (open-ended answer)'), ('mixed', 'Mixed (choices + text)')], default='choice', max_length=10, verbose_name='Question Type'),
        ),
    ]
