# Generated by Django 5.0.6 on 2026-03-19 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0012_answer_text_answer_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='questionnaire.survey', verbose_name='Survey'),
        ),
    ]
