# Generated by Django 5.0.6 on 2026-03-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0014_link_categories_to_surveys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireattempt',
            name='environmental_score',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Environmental Score'),
        ),
        migrations.AlterField(
            model_name='questionnaireattempt',
            name='governance_score',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Governance Score'),
        ),
        migrations.AlterField(
            model_name='questionnaireattempt',
            name='social_score',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Social Score'),
        ),
    ]
