# Generated by Django 5.0.6 on 2026-06-09 00:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0017_question_sector_add_energy_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='environmental_weight',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Environmental Weight'),
        ),
        migrations.AlterField(
            model_name='category',
            name='governance_weight',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Governance Weight'),
        ),
        migrations.AlterField(
            model_name='category',
            name='social_weight',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Social Weight'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['survey', 'is_active', 'sector'], name='q_survey_active_sector_idx'),
        ),
    ]
