# Generated by Django 5.0.6 — extended with deduplication step.
# BH-2: Add UniqueConstraint(user, survey, is_completed=True) to prevent
# duplicate completed attempts at the DB level.
#
# The migration runs in two phases:
#   1. Data migration: for any (user, survey) pair that already has more than
#      one completed attempt, keep only the most recent one and delete the rest.
#      This makes the table clean before the constraint is applied.
#   2. Schema migration: add the UniqueConstraint (partial index on Postgres /
#      filtered index on SQLite ≥ 3.8.9).

from django.conf import settings
from django.db import migrations, models


def deduplicate_completed_attempts(apps, schema_editor):
    """
    Keep only the latest completed attempt per (user, survey) pair.
    Older duplicates are deleted.  In-progress attempts are untouched.
    """
    QuestionnaireAttempt = apps.get_model('questionnaire', 'QuestionnaireAttempt')

    # Find all (user, survey) combos that have more than one completed attempt.
    # We iterate in Python to stay DB-agnostic (no subquery differences).
    seen = set()
    to_delete = []

    # Order by -started_at so the FIRST item we encounter per pair is the newest.
    qs = (
        QuestionnaireAttempt.objects
        .filter(is_completed=True)
        .order_by('-started_at')
        .values_list('id', 'user_id', 'survey_id')
    )
    for pk, user_id, survey_id in qs:
        key = (user_id, survey_id)
        if key in seen:
            to_delete.append(pk)
        else:
            seen.add(key)

    if to_delete:
        QuestionnaireAttempt.objects.filter(id__in=to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0018_add_question_survey_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Phase 1: clean up existing duplicates so Phase 2 can't fail.
        migrations.RunPython(
            deduplicate_completed_attempts,
            reverse_code=migrations.RunPython.noop,
        ),
        # Phase 2: add the constraint (partial index on Postgres/SQLite).
        migrations.AddConstraint(
            model_name='questionnaireattempt',
            constraint=models.UniqueConstraint(
                condition=models.Q(is_completed=True),
                fields=('user', 'survey'),
                name='unique_completed_attempt',
            ),
        ),
    ]
