# Generated by Django 5.0.6 on 2026-05-24 14:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_course_add_metadata_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterField(
            model_name='course',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Description (EN)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description_tr',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Description (TR)'),
        ),
    ]
