"""
Django settings for sustindex project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Fix BUG-19: raise hard error if SECRET_KEY is missing in production so the
# insecure default never silently reaches a live server.
_secret = os.environ.get('SECRET_KEY', '')
if not _secret:
    if os.environ.get('DEBUG', 'True').lower() != 'true':
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured("SECRET_KEY environment variable must be set in production.")
    _secret = 'django-insecure-mk-g2ptinu4*8ojldf$f*&umb_2zn&roo5de_nw9mshcnah^2a'
SECRET_KEY = _secret

# SECURITY WARNING: don't run with debug turned on in production!
# Fix CRITICAL: default is now 'False'. Set DEBUG=True in your .env for local development.
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

# Fix BA: scope hosts instead of wildcard.
# Set ALLOWED_HOSTS env var as comma-separated list in production,
# e.g. "sustindex.com,www.sustindex.com,your-render-slug.onrender.com"
_allowed = os.environ.get('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(',') if h.strip()] if _allowed else ['localhost', '127.0.0.1', '[::1]']
# Fix BUG-13: replace wildcard with named preview host patterns only in dev.
# Wildcard would negate the ALLOWED_HOSTS hardening in production.
if DEBUG:
    ALLOWED_HOSTS += ['.ngrok.io', '.ngrok-free.app', '.onrender.com', 'localhost', '127.0.0.1']


# Application definition

# Optional apps - only add if installed
OPTIONAL_APPS = []

# Check if django-autocomplete-light is installed
try:
    import dal
    import dal_select2
    OPTIONAL_APPS.extend(['dal', 'dal_select2'])
except ImportError:
    pass

# Check if REST framework is installed
try:
    import rest_framework
    import rest_framework_simplejwt
    import corsheaders
    import drf_spectacular
    # Fix L-6: token_blacklist is a sub-app of simplejwt — it must be listed
    # conditionally here, not unconditionally in INSTALLED_APPS, or Django will
    # throw AppRegistryNotReady / ModuleNotFoundError when simplejwt isn't installed.
    OPTIONAL_APPS.extend([
        'rest_framework',
        'rest_framework_simplejwt',
        'rest_framework_simplejwt.token_blacklist',
        'corsheaders',
        'drf_spectacular',
    ])
    REST_FRAMEWORK_INSTALLED = True
except ImportError:
    REST_FRAMEWORK_INSTALLED = False

INSTALLED_APPS = [
    *OPTIONAL_APPS,

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party apps
    'crispy_forms',
    'crispy_bootstrap5',
    'ckeditor',
    'import_export',
    'simple_history',
    # Local apps
    'accounts',
    'questionnaire',
    'elearning',
    'reports',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
]

# Fix R7-09: CorsMiddleware MUST come before WhiteNoiseMiddleware.
# WhiteNoise serves static files and returns early — if CorsMiddleware is
# added after WhiteNoise in the chain it never runs for static-asset requests,
# so cross-origin requests for /static/ assets fail with missing CORS headers.
if REST_FRAMEWORK_INSTALLED:
    MIDDLEWARE.append('corsheaders.middleware.CorsMiddleware')

MIDDLEWARE.extend([
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # Fix R6-15: inject Content-Security-Policy on every response.
    'sustindex.middleware.ContentSecurityPolicyMiddleware',
])

MIDDLEWARE.extend([
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
])

ROOT_URLCONF = 'sustindex.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'sustindex.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if os.environ.get('DATABASE_URL'):
    # Production database (PostgreSQL on Render)
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Development database (SQLite)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True
# L4: USE_L10N was deprecated in Django 4.0 and defaults to True — removed.
USE_TZ = True

LANGUAGES = [
    ('en', 'English'),
    ('tr', 'Türkçe'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Only add STATICFILES_DIRS if static directory exists
import os
if os.path.exists(BASE_DIR / 'static'):
    STATICFILES_DIRS = [BASE_DIR / 'static']
else:
    STATICFILES_DIRS = []

# WhiteNoise configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Custom user model
AUTH_USER_MODEL = 'accounts.User'

# CKEditor
# Fix R5-L-06: replaced 'full' toolbar (all plugins) with an explicit allow-list
# to minimise the content-injection attack surface while still covering the
# formatting operations admins legitimately need.
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source'],
        ],
        'height': 300,
        'width': '100%',
    },
}

# Login/Logout redirects
LOGIN_REDIRECT_URL = 'dashboard'
# Fix: 'home' URL name does not exist in urls.py (the view is commented out).
# Redirect admin logouts to /admin/ login instead of raising NoReverseMatch 500.
LOGOUT_REDIRECT_URL = '/admin/'
LOGIN_URL = 'login'

# REST Framework Configuration (only if installed)
if REST_FRAMEWORK_INSTALLED:
    REST_FRAMEWORK = {
        'DEFAULT_AUTHENTICATION_CLASSES': [
            'rest_framework_simplejwt.authentication.JWTAuthentication',
            'rest_framework.authentication.SessionAuthentication',
        ],
        # Fix R6-12: default to IsAuthenticated so new viewsets are opt-in for
        # public access rather than accidentally exposing read endpoints to
        # unauthenticated users.  AllowAny / IsAuthenticatedOrReadOnly must be
        # set explicitly on the few endpoints that genuinely need it.
        'DEFAULT_PERMISSION_CLASSES': [
            'rest_framework.permissions.IsAuthenticated',
        ],
        'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
        'PAGE_SIZE': 20,
        'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
        # ── Rate limiting ───────────────────────────────────────────────────
        # Applied globally; sensitive endpoints add a stricter scoped throttle
        # on top (LoginRateThrottle / RegisterRateThrottle).
        'DEFAULT_THROTTLE_CLASSES': [
            'rest_framework.throttling.AnonRateThrottle',
            'rest_framework.throttling.UserRateThrottle',
        ],
        'DEFAULT_THROTTLE_RATES': {
            'anon':           '200/day',   # General anonymous API access
            'user':           '2000/day',  # Authenticated user API access
            'login':          '5/minute',  # POST /api/v1/auth/token/
            'register':       '5/hour',    # POST /api/v1/users/register/
            # Fix R4-C-01: limit password-reset requests to prevent email flooding
            # and brute-force token guessing.
            'password_reset': '5/hour',    # POST forgot_password / reset_password
        },
    }

    # JWT Settings
    # Fix H-04: reduce ACCESS_TOKEN_LIFETIME to 5 minutes.
    # Blacklisting only invalidates refresh tokens; stateless access tokens remain
    # valid until expiry even after password change.  A short lifetime limits the
    # exposure window after a token is compromised or a password is changed.
    from datetime import timedelta
    SIMPLE_JWT = {
        'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
        'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
        'ROTATE_REFRESH_TOKENS': True,
        'BLACKLIST_AFTER_ROTATION': True,
    }

    # CORS Settings
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "https://sustindex-academia.vercel.app",
    ]
    # Fix BUG-26: allow additional origins via env var (comma-separated) without a code change.
    _extra_cors = os.environ.get('CORS_EXTRA_ORIGINS', '')
    if _extra_cors:
        CORS_ALLOWED_ORIGINS += [o.strip() for o in _extra_cors.split(',') if o.strip()]

    CORS_ALLOW_CREDENTIALS = True

    # Fix R4-H-05: explicitly list allowed request headers so browsers send
    # Accept-Language (used by DRF serializers to localise names) and the
    # standard Authorization + Content-Type headers without CORS pre-flight rejection.
    from corsheaders.defaults import default_headers as _cors_default_headers
    CORS_ALLOW_HEADERS = list(_cors_default_headers) + [
        'accept-language',   # language preference (TR / EN)
    ]

    # API Documentation
    SPECTACULAR_SETTINGS = {
        'TITLE': 'Sustindex API',
        'DESCRIPTION': 'REST API for Sustainability Assessment Platform',
        'VERSION': '1.0.0',
        'SERVE_INCLUDE_SCHEMA': False,
    }

# ── Email ──────────────────────────────────────────────────────────────────
# Development default: prints email to the console (no SMTP needed).
# Production: set EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
# and the SMTP_* environment variables below.
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST          = os.environ.get('EMAIL_HOST',     'smtp.gmail.com')
EMAIL_PORT          = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS       = os.environ.get('EMAIL_USE_TLS',  'True').lower() == 'true'
EMAIL_HOST_USER     = os.environ.get('EMAIL_HOST_USER',     '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL  = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@sustindex.com')

# URL of the Next.js frontend — used in password-reset emails.
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000')

# ── CSRF trusted origins ───────────────────────────────────────────────────
# Fix R5-L-07: Django 4.x requires CSRF_TRUSTED_ORIGINS when the app runs
# behind a reverse proxy (Render, nginx) — without it, POST/PATCH/DELETE
# requests from the production frontend fail with HTTP 403 CSRF verification.
_csrf_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = (
    [o.strip() for o in _csrf_origins.split(',') if o.strip()]
    if _csrf_origins
    else [
        'http://localhost:3000',
        'http://127.0.0.1:3000',
        'https://sustindex-academia.vercel.app',
    ]
)
# Allow extra origins via env var for staging/feature deploys.
_extra_csrf = os.environ.get('CSRF_EXTRA_ORIGINS', '')
if _extra_csrf:
    CSRF_TRUSTED_ORIGINS += [o.strip() for o in _extra_csrf.split(',') if o.strip()]

# ── Logging ────────────────────────────────────────────────────────────────
# Fix R4-L-03: configure Django's logging so application errors reach the
# console (picked up by Render / Docker log collectors) and, in production,
# so WARNING+ messages from the root logger are never silently discarded.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class':     'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level':    'WARNING',
    },
    'loggers': {
        'django': {
            'handlers':  ['console'],
            'level':     'INFO' if DEBUG else 'WARNING',
            'propagate': False,
        },
        # Application loggers — always at DEBUG in dev, WARNING in prod.
        'accounts':      {'handlers': ['console'], 'level': 'DEBUG' if DEBUG else 'WARNING', 'propagate': False},
        'questionnaire': {'handlers': ['console'], 'level': 'DEBUG' if DEBUG else 'WARNING', 'propagate': False},
        'elearning':     {'handlers': ['console'], 'level': 'DEBUG' if DEBUG else 'WARNING', 'propagate': False},
        'reports':       {'handlers': ['console'], 'level': 'DEBUG' if DEBUG else 'WARNING', 'propagate': False},
    },
}

# Security settings for production
if not DEBUG:
    # Fix M-3: SECURE_BROWSER_XSS_FILTER was removed in Django 4.0 — it is a no-op
    # in Django 5 and modern browsers no longer support the XSS auditor header anyway.
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
