'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'tr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations
const translations = {
  tr: {
    // Navbar
    'nav.features': 'Özellikler',
    'nav.methodology': 'Metodoloji',
    'nav.dashboard': 'Kontrol Paneli',
    'nav.surveys': 'Anketler',
    'nav.about': 'Hakkımızda',
    'nav.history': 'Geçmiş',
    'nav.profile': 'Profil',
    'nav.signin': 'Giriş Yap',
    'nav.getstarted': 'Başlayın',
    'nav.logout': 'Çıkış Yap',
    'nav.language': 'Dil',
    
    // Hero Section
    'hero.badge': 'ESG Değerlendirme Platformu',
    'hero.title1': 'Sürdürülebilirlik',
    'hero.title2': 'Yolculuğunuzu',
    'hero.title3': 'Dönüştürün',
    'hero.description': 'Yapay zeka destekli içgörüler, gerçek zamanlı puanlama ve sürdürülebilir bir gelecek için eyleme dönüştürülebilir önerilerle kapsamlı ESG değerlendirmesi.',
    'hero.getstarted': 'Başlayın',
    'hero.signin': 'Giriş Yap',
    'hero.questions': 'Soru',
    'hero.pillars': 'ESG Sütunu',
    'hero.topgrade': 'En Yüksek Not',
    'hero.cta.start': 'Ücretsiz Değerlendirmeye Başla',
    'hero.cta.learn': 'Daha Fazla Bilgi',
    'hero.badge.secure': 'Güvenli ve Özel',
    'hero.badge.iso': 'ISO Uyumlu',
    'hero.badge.instant': 'Anında Sonuçlar',
    'hero.score': 'ESG Puanı',
    'hero.realtime': 'Gerçek Zamanlı Değerlendirme',
    'hero.environmental': 'Çevresel',
    'hero.social': 'Sosyal',
    'hero.governance': 'Yönetişim',
    'hero.totalpoints': 'Toplam Puan',
    'hero.ranking': 'Sıralama',
    'hero.stats.companies': 'Şirket',
    'hero.stats.accuracy': 'Doğruluk',
    'hero.stats.criteria': 'Kriter',
    'hero.stats.users': 'Kullanıcı',
    
    // Stats Section
    'stats.companies': 'Değerlendirilen Şirket',
    'stats.questions': 'ESG Sorusu',
    'stats.pillars': 'Temel Sütun',
    'stats.satisfaction': 'Memnuniyet Oranı',
    
    // Features Section
    'features.badge': 'Platform Özellikleri',
    'features.title1': 'ESG Mükemmelliği İçin',
    'features.title2': 'İhtiyacınız Olan Her Şey',
    'features.description': 'Kuruluşunuzun sürdürülebilirlik performansını ölçmek, geliştirmek ve sergilemek için kapsamlı araçlar ve içgörüler.',
    
    'features.analytics.title': 'Gerçek Zamanlı Analitik',
    'features.analytics.desc': 'Tüm sürdürülebilirlik boyutlarında anında geri bildirim ve ayrıntılı dökümlerle canlı ESG puanlaması.',
    
    'features.reports.title': 'Profesyonel Raporlar',
    'features.reports.desc': 'Kıyaslama, trend analizi ve eyleme dönüştürülebilir önerilerle yönetici düzeyinde PDF raporları.',
    
    'features.standards.title': 'ISO Standartları',
    'features.standards.desc': 'Uluslararası sürdürülebilirlik standartları ve en iyi uygulamalarla uyumlu değerlendirme çerçevesi.',
    
    'features.insights.title': 'Yapay Zeka İçgörüleri',
    'features.insights.desc': 'Sürdürülebilirlik yolculuğunuzu hızlandırmak için makine öğrenimi destekli akıllı öneriler.',
    
    'features.tracking.title': 'İlerleme Takibi',
    'features.tracking.desc': 'Geçmiş veriler ve trend analiziyle sürdürülebilirlik iyileştirmelerinizi zaman içinde izleyin.',
    
    'features.collaboration.title': 'Ekip İşbirliği',
    'features.collaboration.desc': 'Sorunsuz ekip işbirliği için rol tabanlı izinlerle çok kullanıcılı erişim.',
    
    'features.cta.title': 'Başlamaya hazır mısınız?',
    'features.cta.desc': 'Sürdürülebilirliklerini geliştiren yüzlerce şirkete katılın.',
    'features.cta.button': 'Ücretsiz Denemeye Başla',
    'features.learnmore': 'Daha fazla bilgi',
    
    // Methodology Section
    'methodology.badge': 'Metodolojimiz',
    'methodology.title1': 'Etkilerinizi Nasıl',
    'methodology.title2': 'Ölçüyoruz',
    'methodology.description': 'Kapsamlı ESG değerlendirme çerçevemiz, uluslararası standartlar ve sektör en iyi uygulamaları üzerine inşa edilmiştir.',
    
    'methodology.env.title': 'Çevresel',
    'methodology.env.subtitle': 'Gezegen Etkisi',
    'methodology.env.desc': 'Karbon emisyonları, enerji verimliliği, atık yönetimi, su tasarrufu ve biyoçeşitlilik koruması.',
    'methodology.env.item1': 'Karbon Ayak İzi',
    'methodology.env.item2': 'Enerji Kullanımı',
    'methodology.env.item3': 'Atık Yönetimi',
    'methodology.env.item4': 'Su Tasarrufu',
    
    // Login & Register
    'auth.login.title': 'Giriş Yap',
    'auth.login.welcome': 'Tekrar Hoş Geldiniz',
    'auth.login.username': 'Kullanıcı Adı',
    'auth.login.password': 'Şifre',
    'auth.login.button': 'Giriş Yap',
    'auth.login.loading': 'Giriş yapılıyor...',
    'auth.login.noaccount': 'Hesabınız yok mu?',
    'auth.login.signup': 'Hesap oluştur',
    'auth.login.backhome': 'Ana sayfaya dön',
    'auth.login.secure': 'Güvenli',
    'auth.login.fast': 'Hızlı',
    'auth.login.reliable': 'Güvenilir',
    'auth.login.forgotpassword': 'Şifrenizi mi unuttunuz?',
    
    'auth.register.title': 'Hesap Oluştur',
    'auth.register.subtitle': 'Hesabınızı oluşturun',
    'auth.register.freebadge': 'Ücretsiz Hesap',
    'auth.register.account': 'Hesap Bilgileri',
    'auth.register.personal': 'Kişisel Bilgiler',
    'auth.register.company': 'Şirket Bilgileri',
    'auth.register.security': 'Güvenlik',
    'auth.register.username': 'Kullanıcı Adı',
    'auth.register.email': 'E-posta',
    'auth.register.firstname': 'Ad',
    'auth.register.lastname': 'Soyad',
    'auth.register.companyname': 'Şirket Adı',
    'auth.register.phone': 'Telefon',
    'auth.register.password': 'Şifre',
    'auth.register.confirmpassword': 'Şifreyi Onayla',
    'auth.register.button': 'Hesap Oluştur',
    'auth.register.loading': 'Hesap oluşturuluyor...',
    'auth.register.hasaccount': 'Zaten hesabınız var mı?',
    'auth.register.signin': 'Giriş yap',
    'auth.register.backhome': 'Ana sayfaya dön',
    'auth.register.benefit1.title': 'Gerçek Zamanlı Analitik',
    'auth.register.benefit1.desc': 'ESG performansınızı takip edin',
    'auth.register.benefit2.title': 'Detaylı Raporlar',
    'auth.register.benefit2.desc': 'Kapsamlı PDF\'ler oluşturun',
    'auth.register.benefit3.title': 'Güvenli ve Uyumlu',
    'auth.register.benefit3.desc': 'Endüstri standardı güvenlik',
    'auth.register.placeholder.username': 'Kullanıcı adı seçin',
    'auth.register.placeholder.email': 'ornek@email.com',
    'auth.register.placeholder.firstname': 'Adınız',
    'auth.register.placeholder.lastname': 'Soyadınız',
    'auth.register.placeholder.company': 'Şirketiniz',
    'auth.register.placeholder.phone': '+90 555 123 4567',
    'auth.register.placeholder.password': 'En az 8 karakter',
    'auth.register.placeholder.confirmpassword': 'Şifreyi tekrar girin',
    
    // Dashboard
    'dashboard.welcome': 'Tekrar hoş geldiniz',
    'dashboard.loading': 'Kontrol paneliniz yükleniyor...',
    'dashboard.stats.total': 'Toplam Değerlendirme',
    'dashboard.stats.average': 'Ortalama Puan',
    'dashboard.stats.latest': 'Son Not',
    'dashboard.stats.progress': 'Devam Ediyor',
    'dashboard.esg.title': 'ESG Performansı',
    'dashboard.esg.subtitle': 'Son Değerlendirme Dökümü',
    'dashboard.esg.viewreport': 'Tam Raporu Görüntüle',
    'dashboard.esg.environmental': 'Çevresel',
    'dashboard.esg.social': 'Sosyal',
    'dashboard.esg.governance': 'Yönetişim',
    'dashboard.esg.overall': 'Genel Puan',
    'dashboard.esg.nodata': 'Değerlendirme Verisi Yok',
    'dashboard.esg.nodata.desc': 'ESG performansınızı görmek için ilk değerlendirmenizi tamamlayın',
    'dashboard.esg.start': 'Değerlendirmeye Başla',
    'dashboard.new.title': 'Yeni Değerlendirme',
    'dashboard.new.desc': 'ESG performansınızı ölçmeye başlayın',
    'dashboard.new.button': 'Anketlere Göz At',
    'dashboard.quick.title': 'Hızlı Bağlantılar',
    'dashboard.quick.history': 'Geçmişi Görüntüle',
    'dashboard.quick.profile': 'Profili Düzenle',
    'dashboard.quick.surveys': 'Tüm Anketler',
    'dashboard.recent.title': 'Son Aktivite',
    'dashboard.recent.subtitle': 'En son değerlendirmeleriniz',
    'dashboard.recent.viewall': 'Tümünü Görüntüle',
    'dashboard.recent.empty': 'Henüz Değerlendirme Yok',
    'dashboard.recent.empty.desc': 'ESG ilerlemenizi takip etmek için ilk değerlendirmenizi başlatın',
    'dashboard.recent.getstarted': 'Başlayın',
    'dashboard.recent.score': 'Puan',
    
    // Surveys
    'surveys.title': 'Mevcut Anketler',
    'surveys.subtitle': 'Başlamak için bir sürdürülebilirlik değerlendirmesi seçin',
    'surveys.loading': 'Anketler yükleniyor...',
    'surveys.back': 'Kontrol Paneline Dön',
    'surveys.empty': 'Anket Mevcut Değil',
    'surveys.empty.desc': 'Anket eklemek için lütfen yöneticiyle iletişime geçin.',
    'surveys.active': 'Aktif',
    'surveys.questions': 'soru',
    'surveys.start': 'Değerlendirmeye Başla',
    
    // History
    'history.title': 'Değerlendirme Geçmişi',
    'history.subtitle': 'Tüm sürdürülebilirlik değerlendirmelerinizi görüntüleyin',
    'history.loading': 'Geçmiş yükleniyor...',
    'history.back': 'Kontrol Paneline Dön',
    'history.stats.total': 'Toplam',
    'history.stats.completed': 'Tamamlandı',
    'history.stats.progress': 'Devam Ediyor',
    'history.stats.average': 'Ort. Puan',
    'history.filter.all': 'Tümü',
    'history.filter.completed': 'Tamamlandı',
    'history.filter.progress': 'Devam Ediyor',
    'history.empty': 'Değerlendirme Bulunamadı',
    'history.empty.all': 'İlk değerlendirmenizi başlatın',
    'history.empty.filter': 'değerlendirme bulunamadı',
    'history.new': 'Yeni Değerlendirme Başlat',
    'history.started': 'Başlatıldı',
    'history.completed': 'Tamamlandı',
    'history.continue': 'Devam Et',
    'history.view': 'Sonuçları Görüntüle',
    'history.status.completed': 'Tamamlandı',
    'history.status.progress': 'Devam Ediyor',
    
    // Profile
    'profile.title': 'Profil Ayarları',
    'profile.subtitle': 'Hesap ayarlarınızı ve tercihlerinizi yönetin',
    'profile.loading': 'Profil yükleniyor...',
    'profile.back': 'Kontrol Paneline Dön',
    'profile.tab.info': 'Profil Bilgileri',
    'profile.tab.security': 'Güvenlik',
    'profile.username': 'Kullanıcı Adı',
    'profile.username.note': '(değiştirilemez)',
    'profile.email': 'E-posta',
    'profile.firstname': 'Ad',
    'profile.lastname': 'Soyad',
    'profile.company': 'Şirket Adı',
    'profile.phone': 'Telefon',
    'profile.membership': 'Üyelik Türü',
    'profile.edit': 'Profili Düzenle',
    'profile.save': 'Değişiklikleri Kaydet',
    'profile.saving': 'Kaydediliyor...',
    'profile.cancel': 'İptal',
    'profile.security.title': 'Şifre Değişikliği',
    'profile.security.desc': 'Güvenlik nedenleriyle, şifre değişiklikleri Django yönetici paneli üzerinden yapılmalı veya destek ile iletişime geçilmelidir.',
    'profile.security.actions': 'Hesap İşlemleri',
    'profile.security.logout': 'Tüm Cihazlardan Çıkış Yap',
    
    'methodology.social.title': 'Sosyal',
    'methodology.social.subtitle': 'İnsanlar Önce',
    'methodology.social.desc': 'Çalışan refahı, çeşitlilik ve kapsayıcılık, toplum katılımı, sağlık ve güvenlik ve insan hakları.',
    'methodology.social.item1': 'Çalışan Eğitimi',
    'methodology.social.item2': 'Çeşitlilik Politikaları',
    'methodology.social.item3': 'Toplum Etkisi',
    'methodology.social.item4': 'Sağlık ve Güvenlik',
    
    'methodology.gov.title': 'Yönetişim',
    'methodology.gov.subtitle': 'Etik Liderlik',
    'methodology.gov.desc': 'Yönetim kurulu bağımsızlığı, şeffaflık, etik programları, yolsuzlukla mücadele ve paydaş katılımı.',
    'methodology.gov.item1': 'Yönetim Yapısı',
    'methodology.gov.item2': 'Şeffaflık',
    'methodology.gov.item3': 'Etik Programları',
    'methodology.gov.item4': 'Uyumluluk',
    
    'methodology.results.title': 'Sonuçlar',
    'methodology.results.subtitle': 'Eyleme Dönüştürülebilir İçgörüler',
    'methodology.results.desc': 'A+ ile D arasında notlar, kıyaslama ve kişiselleştirilmiş iyileştirme yol haritası ile kapsamlı puanlama.',
    'methodology.results.item1': 'Puan Analizi',
    'methodology.results.item2': 'Kıyaslama',
    'methodology.results.item3': 'Öneriler',
    'methodology.results.item4': 'PDF Raporu',
    
    'methodology.process.title': 'Değerlendirme Süreci',
    'methodology.process.signup': 'Kayıt Ol',
    'methodology.process.signup.desc': 'Hesap oluştur',
    'methodology.process.answer': 'Cevapla',
    'methodology.process.answer.desc': '12 soru',
    'methodology.process.upload': 'Yükle',
    'methodology.process.upload.desc': 'Belgeler',
    'methodology.process.calculate': 'Hesapla',
    'methodology.process.calculate.desc': 'ESG puanı',
    'methodology.process.download': 'İndir',
    'methodology.process.download.desc': 'PDF raporu',
    
    'methodology.cta.title': 'Sürdürülebilirlik Yolculuğunuza Başlamaya Hazır mısınız?',
    'methodology.cta.desc': 'ESG performanslarını ölçen ve geliştiren önde gelen kuruluşlara katılın.',
    'methodology.cta.start': 'Ücretsiz Değerlendirmeye Başla',
    'methodology.cta.signin': 'Giriş Yap',
    'methodology.scoring.title': 'Puanlama Sistemi',
    
    // Footer
    'footer.description': 'Kuruluşların sürdürülebilirlik performanslarını ölçmelerine, geliştirmelerine ve sergilemelerine güç veriyoruz.',
    'footer.platform': 'Platform',
    'footer.about': 'Hakkımızda',
    'footer.features': 'Özellikler',
    'footer.methodology': 'Metodoloji',
    'footer.assessments': 'Değerlendirmeler',
    'footer.resources': 'Kaynaklar',
    'footer.documentation': 'Dokümantasyon',
    'footer.api': 'API Referansı',
    'footer.support': 'Destek',
    'footer.blog': 'Blog',
    'footer.getstarted': 'Başlayın',
    'footer.signup': 'Kayıt Ol',
    'footer.signin': 'Giriş Yap',
    'footer.pricing': 'Fiyatlandırma',
    'footer.contact': 'İletişim',
    'footer.rights': 'Tüm hakları saklıdır.',
    'footer.privacy': 'Gizlilik Politikası',
    'footer.terms': 'Hizmet Şartları',
    'footer.cookies': 'Çerez Politikası',
    
    // Questionnaire
    'questionnaire.loading': 'Anket yükleniyor...',
    'questionnaire.question': 'Soru',
    'questionnaire.of': '/',
    'questionnaire.complete': 'Tamamlandı',
    'questionnaire.previous': 'Önceki',
    'questionnaire.next': 'Sonraki',
    'questionnaire.submit': 'Değerlendirmeyi Gönder',
    'questionnaire.submitting': 'Gönderiliyor...',
    'questionnaire.multiple': 'Birden fazla cevap seçebilirsiniz',
    'questionnaire.upload': 'Destekleyici Belgeler Yükle (İsteğe Bağlı)',
    'questionnaire.choose': 'Dosya Seç',
    'questionnaire.nofile': 'Dosya seçilmedi',
    'questionnaire.file': 'dosya',
    'questionnaire.files': 'dosya',
    'questionnaire.selected': 'seçildi',
    'questionnaire.answer': 'Lütfen göndermeden önce bu soruyu cevaplayın',
    'questionnaire.textAnswer': 'Cevabınız',
    'questionnaire.textPlaceholder': 'Cevabınızı buraya yazın...',
    
    // Not Found Page
    'notfound.title': 'Sayfa Bulunamadı',
    'notfound.description': 'Üzgünüz, aradığınız sayfa bulunamadı.',
    'notfound.home': 'Ana Sayfaya Dön',
    'notfound.dashboard': 'Kontrol Paneline Git',
    
    // About Page
    'about.title': 'Hakkımızda',
    'about.subtitle': 'Profesyonel Sürdürülebilirlik Değerlendirme Platformu',
    'about.company.title': 'Academia Danışmanlık',
    'about.company.desc': 'Sustindex, Academia Danışmanlık\'ın sürdürülebilirlik ve ESG değerlendirme platformudur. Academia Danışmanlık, şirketlere stratejik danışmanlık, eğitim ve dijital çözümler sunarak sürdürülebilirlik yolculuklarında rehberlik eder.',
    'about.company.visit': 'Academia Danışmanlık\'ı Ziyaret Edin',
    'about.mission.title': 'Misyonumuz',
    'about.mission.desc': 'Sustindex, şirketlerin sürdürülebilirlik performanslarını ölçmelerine, anlamalarına ve geliştirmelerine yardımcı olmaya kendini adamıştır. Uluslararası standartlara ve en iyi uygulamalara dayalı kapsamlı ESG (Çevresel, Sosyal ve Yönetişim) değerlendirmeleri sağlıyoruz.',
    'about.offer.title': 'Neler Sunuyoruz',
    'about.offer.assessment.title': 'Kapsamlı Değerlendirme',
    'about.offer.assessment.desc': 'Çevresel, Sosyal ve Yönetişim yönlerini kapsayan 30+ sürdürülebilirlik göstergesi üzerinden detaylı değerlendirme.',
    'about.offer.reports.title': 'Profesyonel Raporlar',
    'about.offer.reports.desc': 'Detaylı analiz, kıyaslama ve eyleme dönüştürülebilir önerilerle yönetici düzeyinde raporlar.',
    'about.offer.standards.title': 'Endüstri Standartları',
    'about.offer.standards.desc': 'GRI, SASB ve UN SDG\'ler dahil uluslararası tanınmış çerçevelere dayalı.',
    'about.offer.insights.title': 'Eyleme Dönüştürülebilir İçgörüler',
    'about.offer.insights.desc': 'Sürdürülebilirlik performansınızı geliştirmek için önceliklendirilmiş öneriler alın.',
    'about.methodology.title': 'Metodolojimiz',
    'about.methodology.env': 'Çevresel Değerlendirme',
    'about.methodology.env.desc': 'Atık yönetimi, enerji kullanımı, karbon ayak izi, su tasarrufu ve çevre politikalarını değerlendirin.',
    'about.methodology.social': 'Sosyal Sorumluluk',
    'about.methodology.social.desc': 'Çalışan eğitimi, çeşitlilik ve kapsayıcılık, toplum katılımı, sağlık ve güvenlik önlemlerini değerlendirin.',
    'about.methodology.gov': 'Kurumsal Yönetişim',
    'about.methodology.gov.desc': 'Yönetim kurulu bağımsızlığı, şeffaflık, etik programları ve paydaş katılımını inceleyin.',
    'about.methodology.scoring': 'Puanlama ve Notlandırma',
    'about.methodology.scoring.desc': 'A+\'dan D\'ye kadar notlarla ağırlıklı puanlama sistemi, net performans göstergeleri sağlar.',
    'about.contact.title': 'İletişim Bilgileri',
    'about.contact.address': 'Adres',
    'about.contact.phone': 'Telefon',
    'about.contact.fax': 'Faks',
    'about.cta.title': 'Başlamaya Hazır mısınız?',
    'about.cta.desc': 'Sürdürülebilirlik yolculuğunuza bugün başlayın',
    'about.cta.button': 'Ücretsiz Hesap Oluştur',
    
    // Error Messages
    'error.login.failed': 'Giriş başarısız. Lütfen kimlik bilgilerinizi kontrol edin.',
    'error.register.failed': 'Kayıt başarısız. Lütfen tekrar deneyin.',
    'error.register.password': 'Şifreler eşleşmiyor',
    'error.profile.update.success': 'Profil başarıyla güncellendi!',
    'error.profile.update.failed': 'Profil güncellenemedi. Lütfen tekrar deneyin.',
    'error.questionnaire.init': 'Anket başlatılamadı',
    'error.questionnaire.noid': 'Anket ID bulunamadı!',
    'error.questionnaire.answer': 'Lütfen göndermeden önce bu soruyu cevaplayın.',
    'error.questionnaire.save': 'Cevap kaydedilemedi. Lütfen tekrar deneyin.',
    'error.questionnaire.submit': 'Gönderim başarısız',
    'error.questionnaire.success': 'Değerlendirme başarıyla tamamlandı!',
    'error.results.load': 'Sonuçlar yüklenemedi',
    
    // Results
    'results.loading': 'Sonuçlar yükleniyor...',
    'results.complete': 'Değerlendirme Tamamlandı!',
    'results.completedon': 'Tamamlanma Tarihi',
    'results.overall': 'Genel Puan',
    'results.outof': '100 üzerinden',
    'results.environmental': 'Çevresel',
    'results.social': 'Sosyal',
    'results.governance': 'Yönetişim',
    'results.recommendations': 'Öneriler',
    'results.priority': 'Öncelik',
    'results.high': 'Yüksek',
    'results.medium': 'Orta',
    'results.low': 'Düşük',
    'results.answers': 'Cevaplarınız',
    'results.question': 'Soru',
    'results.score': 'Puan',
    'results.notes': 'Notlar',
    'results.documents': 'Yüklenen Belgeler',
    'results.download': 'İndir',
    'results.export': 'PDF Olarak Dışa Aktar',
    'results.exporting': 'Dışa aktarılıyor...',
    'results.back': 'Kontrol Paneline Dön',
    'results.exporterror': 'PDF dışa aktarılamadı. Lütfen tekrar deneyin.',
  },
  en: {
    // Navbar
    'nav.features': 'Features',
    'nav.methodology': 'Methodology',
    'nav.dashboard': 'Dashboard',
    'nav.surveys': 'Surveys',
    'nav.about': 'About',
    'nav.history': 'History',
    'nav.profile': 'Profile',
    'nav.signin': 'Sign In',
    'nav.getstarted': 'Get Started',
    'nav.logout': 'Logout',
    'nav.language': 'Language',
    
    // Hero Section
    'hero.badge': 'ESG Assessment Platform',
    'hero.title1': 'Transform Your',
    'hero.title2': 'Sustainability',
    'hero.title3': 'Journey',
    'hero.description': 'Comprehensive ESG assessment with AI-powered insights, real-time scoring, and actionable recommendations for a sustainable future.',
    'hero.getstarted': 'Get Started',
    'hero.signin': 'Sign In',
    'hero.questions': 'Questions',
    'hero.pillars': 'ESG Pillars',
    'hero.topgrade': 'Top Grade',
    'hero.cta.start': 'Start Free Assessment',
    'hero.cta.learn': 'Learn More',
    'hero.badge.secure': 'Secure & Private',
    'hero.badge.iso': 'ISO Compliant',
    'hero.badge.instant': 'Instant Results',
    'hero.score': 'ESG Score',
    'hero.realtime': 'Real-time Assessment',
    'hero.environmental': 'Environmental',
    'hero.social': 'Social',
    'hero.governance': 'Governance',
    'hero.totalpoints': 'Total Points',
    'hero.ranking': 'Ranking',
    'hero.stats.companies': 'Companies',
    'hero.stats.accuracy': 'Accuracy',
    'hero.stats.criteria': 'Criteria',
    'hero.stats.users': 'Users',
    
    // Stats Section
    'stats.companies': 'Companies Assessed',
    'stats.questions': 'ESG Questions',
    'stats.pillars': 'Core Pillars',
    'stats.satisfaction': 'Satisfaction Rate',
    
    // Features Section
    'features.badge': 'Platform Features',
    'features.title1': 'Everything You Need for',
    'features.title2': 'ESG Excellence',
    'features.description': 'Comprehensive tools and insights to measure, improve, and showcase your organization\'s sustainability performance.',
    
    'features.analytics.title': 'Real-Time Analytics',
    'features.analytics.desc': 'Live ESG scoring with instant feedback and detailed breakdowns across all sustainability dimensions.',
    
    'features.reports.title': 'Professional Reports',
    'features.reports.desc': 'Executive-ready PDF reports with benchmarking, trends analysis, and actionable recommendations.',
    
    'features.standards.title': 'ISO Standards',
    'features.standards.desc': 'Assessment framework aligned with international sustainability standards and best practices.',
    
    'features.insights.title': 'AI Insights',
    'features.insights.desc': 'Smart recommendations powered by machine learning to accelerate your sustainability journey.',
    
    'features.tracking.title': 'Progress Tracking',
    'features.tracking.desc': 'Monitor your sustainability improvements over time with historical data and trend analysis.',
    
    'features.collaboration.title': 'Team Collaboration',
    'features.collaboration.desc': 'Multi-user access with role-based permissions for seamless team collaboration.',
    
    'features.cta.title': 'Ready to get started?',
    'features.cta.desc': 'Join hundreds of companies improving their sustainability.',
    'features.cta.button': 'Start Free Trial',
    'features.learnmore': 'Learn more',
    
    // Methodology Section
    'methodology.badge': 'Our Methodology',
    'methodology.title1': 'How We Measure',
    'methodology.title2': 'Your Impact',
    'methodology.description': 'Our comprehensive ESG assessment framework is built on international standards and industry best practices.',
    
    'methodology.env.title': 'Environmental',
    'methodology.env.subtitle': 'Planet Impact',
    'methodology.env.desc': 'Carbon emissions, energy efficiency, waste management, water conservation, and biodiversity protection.',
    'methodology.env.item1': 'Carbon Footprint',
    'methodology.env.item2': 'Energy Usage',
    'methodology.env.item3': 'Waste Management',
    'methodology.env.item4': 'Water Conservation',
    
    'methodology.social.title': 'Social',
    'methodology.social.subtitle': 'People First',
    'methodology.social.desc': 'Employee welfare, diversity & inclusion, community engagement, health & safety, and human rights.',
    'methodology.social.item1': 'Employee Training',
    'methodology.social.item2': 'Diversity Policies',
    'methodology.social.item3': 'Community Impact',
    'methodology.social.item4': 'Health & Safety',
    
    'methodology.gov.title': 'Governance',
    'methodology.gov.subtitle': 'Ethical Leadership',
    'methodology.gov.desc': 'Board independence, transparency, ethics programs, anti-corruption, and stakeholder engagement.',
    'methodology.gov.item1': 'Board Structure',
    'methodology.gov.item2': 'Transparency',
    'methodology.gov.item3': 'Ethics Programs',
    'methodology.gov.item4': 'Compliance',
    
    'methodology.results.title': 'Results',
    'methodology.results.subtitle': 'Actionable Insights',
    'methodology.results.desc': 'Comprehensive scoring with A+ to D grades, benchmarking, and personalized improvement roadmap.',
    'methodology.results.item1': 'Score Analysis',
    'methodology.results.item2': 'Benchmarking',
    'methodology.results.item3': 'Recommendations',
    'methodology.results.item4': 'PDF Report',
    
    'methodology.process.title': 'Assessment Process',
    'methodology.process.signup': 'Sign Up',
    'methodology.process.signup.desc': 'Create account',
    'methodology.process.answer': 'Answer',
    'methodology.process.answer.desc': '12 questions',
    'methodology.process.upload': 'Upload',
    'methodology.process.upload.desc': 'Documents',
    'methodology.process.calculate': 'Calculate',
    'methodology.process.calculate.desc': 'ESG score',
    'methodology.process.download': 'Download',
    'methodology.process.download.desc': 'PDF report',
    
    'methodology.cta.title': 'Ready to Start Your Sustainability Journey?',
    'methodology.cta.desc': 'Join leading organizations in measuring and improving their ESG performance.',
    'methodology.cta.start': 'Start Free Assessment',
    'methodology.cta.signin': 'Sign In',
    'methodology.scoring.title': 'Scoring System',
    
    // Footer
    'footer.description': 'Empowering organizations to measure, improve, and showcase their sustainability performance.',
    'footer.platform': 'Platform',
    'footer.about': 'About Us',
    'footer.features': 'Features',
    'footer.methodology': 'Methodology',
    'footer.assessments': 'Assessments',
    'footer.resources': 'Resources',
    'footer.documentation': 'Documentation',
    'footer.api': 'API Reference',
    'footer.support': 'Support',
    'footer.blog': 'Blog',
    'footer.getstarted': 'Get Started',
    'footer.signup': 'Sign Up',
    'footer.signin': 'Sign In',
    'footer.pricing': 'Pricing',
    'footer.contact': 'Contact',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.cookies': 'Cookie Policy',
    
    // Questionnaire
    'questionnaire.loading': 'Loading questionnaire...',
    'questionnaire.question': 'Question',
    'questionnaire.of': 'of',
    'questionnaire.complete': 'Complete',
    'questionnaire.previous': 'Previous',
    'questionnaire.next': 'Next',
    'questionnaire.submit': 'Submit Assessment',
    'questionnaire.submitting': 'Submitting...',
    'questionnaire.multiple': 'You can select multiple answers',
    'questionnaire.upload': 'Upload Supporting Documents (Optional)',
    'questionnaire.choose': 'Choose Files',
    'questionnaire.nofile': 'No file chosen',
    'questionnaire.file': 'file',
    'questionnaire.files': 'files',
    'questionnaire.selected': 'selected',
    'questionnaire.answer': 'Please answer this question before submitting',
    'questionnaire.textAnswer': 'Your Answer',
    'questionnaire.textPlaceholder': 'Type your answer here...',
    
    // Not Found Page
    'notfound.title': 'Page Not Found',
    'notfound.description': 'Sorry, we couldn\'t find the page you\'re looking for.',
    'notfound.home': 'Go Home',
    'notfound.dashboard': 'Go to Dashboard',
    
    // About Page
    'about.title': 'About Us',
    'about.subtitle': 'Professional Sustainability Assessment Platform',
    'about.company.title': 'Academia Consulting',
    'about.company.desc': 'Sustindex is the sustainability and ESG assessment platform of Academia Consulting. Academia Consulting guides companies on their sustainability journey by providing strategic consulting, training, and digital solutions.',
    'about.company.visit': 'Visit Academia Consulting',
    'about.mission.title': 'Our Mission',
    'about.mission.desc': 'Sustindex is dedicated to helping companies measure, understand, and improve their sustainability performance. We provide comprehensive ESG (Environmental, Social, and Governance) assessments based on international standards and best practices.',
    'about.offer.title': 'What We Offer',
    'about.offer.assessment.title': 'Comprehensive Assessment',
    'about.offer.assessment.desc': 'Detailed evaluation across 30+ sustainability indicators covering Environmental, Social, and Governance aspects.',
    'about.offer.reports.title': 'Professional Reports',
    'about.offer.reports.desc': 'Executive-ready reports with detailed analysis, benchmarking, and actionable recommendations.',
    'about.offer.standards.title': 'Industry Standards',
    'about.offer.standards.desc': 'Based on internationally recognized frameworks including GRI, SASB, and UN SDGs.',
    'about.offer.insights.title': 'Actionable Insights',
    'about.offer.insights.desc': 'Receive prioritized recommendations to improve your sustainability performance.',
    'about.methodology.title': 'Our Methodology',
    'about.methodology.env': 'Environmental Assessment',
    'about.methodology.env.desc': 'Evaluate waste management, energy usage, carbon footprint, water conservation, and environmental policies.',
    'about.methodology.social': 'Social Responsibility',
    'about.methodology.social.desc': 'Assess employee training, diversity & inclusion, community engagement, health & safety measures.',
    'about.methodology.gov': 'Corporate Governance',
    'about.methodology.gov.desc': 'Review board independence, transparency, ethics programs, and stakeholder engagement.',
    'about.methodology.scoring': 'Scoring & Grading',
    'about.methodology.scoring.desc': 'Weighted scoring system with grades from A+ to D, providing clear performance indicators.',
    'about.contact.title': 'Contact Information',
    'about.contact.address': 'Address',
    'about.contact.phone': 'Phone',
    'about.contact.fax': 'Fax',
    'about.cta.title': 'Ready to Get Started?',
    'about.cta.desc': 'Begin your sustainability journey today',
    'about.cta.button': 'Create Free Account',
    
    // Error Messages
    'error.login.failed': 'Login failed. Please check your credentials.',
    'error.register.failed': 'Registration failed. Please try again.',
    'error.register.password': 'Passwords do not match',
    'error.profile.update.success': 'Profile updated successfully!',
    'error.profile.update.failed': 'Failed to update profile. Please try again.',
    'error.questionnaire.init': 'Failed to initialize questionnaire',
    'error.questionnaire.noid': 'No attempt ID found!',
    'error.questionnaire.answer': 'Please answer this question before submitting.',
    'error.questionnaire.save': 'Failed to save answer. Please try again.',
    'error.questionnaire.submit': 'Submission failed',
    'error.questionnaire.success': 'Assessment completed successfully!',
    'error.results.load': 'Failed to load results',
    
    // Results
    'results.loading': 'Loading results...',
    'results.complete': 'Assessment Complete!',
    'results.completedon': 'Completed on',
    'results.overall': 'Overall Score',
    'results.outof': 'out of 100',
    'results.environmental': 'Environmental',
    'results.social': 'Social',
    'results.governance': 'Governance',
    'results.recommendations': 'Recommendations',
    'results.priority': 'Priority',
    'results.high': 'High',
    'results.medium': 'Medium',
    'results.low': 'Low',
    'results.answers': 'Your Answers',
    'results.question': 'Question',
    'results.score': 'Score',
    'results.notes': 'Notes',
    'results.documents': 'Uploaded Documents',
    'results.download': 'Download',
    'results.export': 'Export as PDF',
    'results.exporting': 'Exporting...',
    'results.back': 'Back to Dashboard',
    'results.exporterror': 'Failed to export PDF. Please try again.',
    
    // Login & Register
    'auth.login.title': 'Sign In',
    'auth.login.welcome': 'Welcome Back',
    'auth.login.username': 'Username',
    'auth.login.password': 'Password',
    'auth.login.button': 'Sign In',
    'auth.login.loading': 'Signing in...',
    'auth.login.noaccount': 'Don\'t have an account?',
    'auth.login.signup': 'Create account',
    'auth.login.backhome': 'Back to home',
    'auth.login.secure': 'Secure',
    'auth.login.fast': 'Fast',
    'auth.login.reliable': 'Reliable',
    'auth.login.forgotpassword': 'Forgot your password?',
    
    'auth.register.title': 'Create Account',
    'auth.register.subtitle': 'Create your account',
    'auth.register.freebadge': 'Free Account',
    'auth.register.account': 'Account Information',
    'auth.register.personal': 'Personal Information',
    'auth.register.company': 'Company Information',
    'auth.register.security': 'Security',
    'auth.register.username': 'Username',
    'auth.register.email': 'Email',
    'auth.register.firstname': 'First Name',
    'auth.register.lastname': 'Last Name',
    'auth.register.companyname': 'Company Name',
    'auth.register.phone': 'Phone',
    'auth.register.password': 'Password',
    'auth.register.confirmpassword': 'Confirm Password',
    'auth.register.button': 'Create Account',
    'auth.register.loading': 'Creating account...',
    'auth.register.hasaccount': 'Already have an account?',
    'auth.register.signin': 'Sign in',
    'auth.register.backhome': 'Back to home',
    'auth.register.benefit1.title': 'Real-time Analytics',
    'auth.register.benefit1.desc': 'Track your ESG performance',
    'auth.register.benefit2.title': 'Detailed Reports',
    'auth.register.benefit2.desc': 'Generate comprehensive PDFs',
    'auth.register.benefit3.title': 'Secure & Compliant',
    'auth.register.benefit3.desc': 'Industry-standard security',
    'auth.register.placeholder.username': 'Choose a username',
    'auth.register.placeholder.email': 'your@email.com',
    'auth.register.placeholder.firstname': 'John',
    'auth.register.placeholder.lastname': 'Doe',
    'auth.register.placeholder.company': 'Your Company',
    'auth.register.placeholder.phone': '+1 234 567 8900',
    'auth.register.placeholder.password': 'Min 8 characters',
    'auth.register.placeholder.confirmpassword': 'Repeat password',
    
    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.loading': 'Loading your dashboard...',
    'dashboard.stats.total': 'Total Assessments',
    'dashboard.stats.average': 'Average Score',
    'dashboard.stats.latest': 'Latest Grade',
    'dashboard.stats.progress': 'In Progress',
    'dashboard.esg.title': 'ESG Performance',
    'dashboard.esg.subtitle': 'Latest Assessment Breakdown',
    'dashboard.esg.viewreport': 'View Full Report',
    'dashboard.esg.environmental': 'Environmental',
    'dashboard.esg.social': 'Social',
    'dashboard.esg.governance': 'Governance',
    'dashboard.esg.overall': 'Overall Score',
    'dashboard.esg.nodata': 'No Assessment Data',
    'dashboard.esg.nodata.desc': 'Complete your first assessment to see your ESG performance',
    'dashboard.esg.start': 'Start Assessment',
    'dashboard.new.title': 'New Assessment',
    'dashboard.new.desc': 'Start measuring your ESG performance',
    'dashboard.new.button': 'Browse Surveys',
    'dashboard.quick.title': 'Quick Links',
    'dashboard.quick.history': 'View History',
    'dashboard.quick.profile': 'Edit Profile',
    'dashboard.quick.surveys': 'All Surveys',
    'dashboard.recent.title': 'Recent Activity',
    'dashboard.recent.subtitle': 'Your latest assessments',
    'dashboard.recent.viewall': 'View All',
    'dashboard.recent.empty': 'No Assessments Yet',
    'dashboard.recent.empty.desc': 'Start your first assessment to track your ESG progress',
    'dashboard.recent.getstarted': 'Get Started',
    'dashboard.recent.score': 'Score',
    
    // Surveys
    'surveys.title': 'Available Surveys',
    'surveys.subtitle': 'Choose a sustainability assessment to begin',
    'surveys.loading': 'Loading surveys...',
    'surveys.back': 'Back to Dashboard',
    'surveys.empty': 'No Surveys Available',
    'surveys.empty.desc': 'Please contact administrator to add surveys.',
    'surveys.active': 'Active',
    'surveys.questions': 'questions',
    'surveys.start': 'Start Assessment',
    
    // History
    'history.title': 'Assessment History',
    'history.subtitle': 'View all your sustainability assessments',
    'history.loading': 'Loading history...',
    'history.back': 'Back to Dashboard',
    'history.stats.total': 'Total',
    'history.stats.completed': 'Completed',
    'history.stats.progress': 'In Progress',
    'history.stats.average': 'Avg Score',
    'history.filter.all': 'All',
    'history.filter.completed': 'Completed',
    'history.filter.progress': 'In Progress',
    'history.empty': 'No Assessments Found',
    'history.empty.all': 'Start your first assessment to see it here',
    'history.empty.filter': 'assessments found',
    'history.new': 'Start New Assessment',
    'history.started': 'Started',
    'history.completed': 'Completed',
    'history.continue': 'Continue',
    'history.view': 'View Results',
    'history.status.completed': 'Completed',
    'history.status.progress': 'In Progress',
    
    // Profile
    'profile.title': 'Profile Settings',
    'profile.subtitle': 'Manage your account settings and preferences',
    'profile.loading': 'Loading profile...',
    'profile.back': 'Back to Dashboard',
    'profile.tab.info': 'Profile Information',
    'profile.tab.security': 'Security',
    'profile.username': 'Username',
    'profile.username.note': '(cannot be changed)',
    'profile.email': 'Email',
    'profile.firstname': 'First Name',
    'profile.lastname': 'Last Name',
    'profile.company': 'Company Name',
    'profile.phone': 'Phone',
    'profile.membership': 'Membership Type',
    'profile.edit': 'Edit Profile',
    'profile.save': 'Save Changes',
    'profile.saving': 'Saving...',
    'profile.cancel': 'Cancel',
    'profile.security.title': 'Password Change',
    'profile.security.desc': 'For security reasons, password changes must be done through the Django admin panel or contact support.',
    'profile.security.actions': 'Account Actions',
    'profile.security.logout': 'Logout from All Devices',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('tr'); // Default: Turkish

  useEffect(() => {
    // Load language from localStorage
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'tr' || savedLanguage === 'en')) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    const translation = translations[language] as Record<string, string>;
    return translation[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
